# Datasource
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.devservices.enabled=false

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.validate-in-dev-mode=false

quarkus.panache.default-page-size=10

mp.jwt.verify.issuer=ms-auth
mp.jwt.verify.publickey.location=publicKey.pem

quarkus.http.port=8082

mp.messaging.outgoing.course-archived.connector=smallrye-kafka
mp.messaging.outgoing.course-archived.topic=course.archived
mp.messaging.outgoing.course-archived.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
